services:
  mock-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3090:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start
    restart: unless-stopped
